version: "3.8"

services:

  db:
   image:
     postgres: 15.1-alpine
   environment:
     POSTGRES_USER: ${DB_USER}
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
   volumes:
     - todolist_P9_plata_14:/var/lib/postgresql/data
   healthcheck:
     test: pg_isready -U ${DB_USER} -d ${DB_NAME}
     interval: 3s
     timeout: 2s
     retries: 10
   ports:
     - "5433:5432"

volumes:
  todolist_pg_data_14: