# Generated by Django 4.0.1 on 2023-07-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_tguser_verification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Пользователь Бота', 'verbose_name_plural': 'Пользователи Бота'},
        ),
    ]
